version: '3'
services:
  sqldb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: ${DNSQLDB_SA_PWD}
    ports:
      - "1401:1433"